# Generated by Django 3.2.9 on 2021-11-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
