# Generated by Django 3.2.9 on 2021-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211116_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stop_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
