# Generated by Django 3.2.9 on 2021-11-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211118_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity')], default='crypto', max_length=10),
        ),
    ]
