# Generated by Django 3.2.9 on 2022-01-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Portfolio',
        ),
    ]
