# Generated by Django 3.2.9 on 2022-01-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220107_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='option_type',
            field=models.CharField(choices=[('calls', 'Call'), ('puts', 'Put')], default='call', max_length=10),
        ),
    ]
