# Generated by Django 3.2.9 on 2022-01-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_asset_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[('investment', 'Investment'), ('savings', 'Savings')], default='investment', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='option_type',
            field=models.CharField(choices=[('calls', 'Call'), ('puts', 'Put')], default='calls', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stop_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
